### PR TITLE
Upgrade to node 18.0.0

### PR DESCRIPTION
**Pull request by brodoin**
Updating to node 18.0.0 changes some requirements for importing json files, namely that they require the assertion that the files are indeed json files. This then required an update to the linter, but the eslint community is waiting for standards to reach phase 4 before they implement the change, so a babel linting plugin is added to make it all work.

### CODE REVIEW

**Review by MichaelTaylor3D — CHANGES_REQUESTED** [review]
Is there a reason we are upgrading? or is it a just because we can? I would like to avoid upgrading the node version unless there is a good reason.

**Review by MichaelTaylor3D — CHANGES_REQUESTED** [review]
Can we please just NOT do this?

**Review by MichaelTaylor3D — CHANGES_REQUESTED** [review]
Please refrain from PRs that refactor entire systems of the application until im back from leave.

**Comment by TheLastCicada** [comment]
On hold until Michael is back.  Leaving this pull request here for reference when we tackle this in the near future.

**Pull request closed without merging**
